#!/usr/local/bin/python3
import tkinter as tk
from gui_test.run_shells import RunShell
# from gui_test.btn_factory import make_btn



window = tk.Tk()
window.title('ip192')
window.geometry('500' + 'x' + '500' + '+300+300')

# 设置的滚动条功能还不完整
# sb = tk.Scrollbar(window)
# sb.pack(side = tk.RIGHT, fill = tk.Y)


cmd = RunShell()

lb = tk.Listbox(window, height='20') # height指的是垂直方向有多少item
for item in cmd.ls_l():
    lb.insert(tk.END, item)
lb.pack()

btn = tk.Button(window, text='后退')
btn.pack()



def click(event):
    click_item = lb.get(lb.curselection())
    lb.delete(0, lb.size())
    cmd.cd_to(click_item)
    for it in cmd.ls_l():
        lb.insert(tk.END, it)

def back(event):
    lb.delete(0, lb.size())
    cmd.cd_to('../')
    for it in cmd.ls_l():
        lb.insert(tk.END, it)

lb.bind('<Double-Button-1>', click)

btn.bind('<Button-1>', back)




window.mainloop()
