#!/usr/local/bin/python3
import tkinter as tk
from gui_test.label_factory import make_label
from gui_test.list_box import list_box
from gui_test.btn_factory import make_btn
from gui_test.run_shells import ls_l


window = tk.Tk()
window.title('ip192')
window.geometry('500' + 'x' + '500' + '+300+300')

# 设置的滚动条功能还不完整
# sb = tk.Scrollbar(window)
# sb.pack(side = tk.RIGHT, fill = tk.Y)


# make_label(window, ls_l())
list_box(window, ls_l())
make_btn(window, ['后退', '进入', '新建'])


window.mainloop()
